# Config file for automatic testing at travis-ci.org

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env:
        - TOX_ENV=django111-py35
        - TOX_ENV=django2-py35
        - TOX_ENV=django21-py35
        - TOX_ENV=django22-py35
    - python: 3.6
      env:
        - TOX_ENV=django111-py36
        - TOX_ENV=django2-py36
        - TOX_ENV=django21-py36
        - TOX_ENV=django22-py36
    - python: 3.7
      dist: xenial
      env:
        - TOX_ENV=django111-py37
        - TOX_ENV=django2-py37
        - TOX_ENV=django21-py37
        - TOX_ENV=django22-py37


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
